package docsgen

import (
	"fmt"
	"html"
	"strconv"
	"strings"

	"github.com/serkanalgur/termmosaic/buffer"
	"github.com/serkanalgur/termmosaic/headless"
)

// cssFile is the stylesheet every generated .html links to. It is written
// alongside the captures by Generate from the same captureCSS constant the
// markup documents, so the two cannot disagree.
const cssFile = "capture.css"

// captureCSS is the stylesheet for the captures.
//
// It exists because a capture is a cell GRID and a browser is not a terminal,
// and the difference has to be pinned rather than hoped for:
//
//   - A fixed monospace face with font-variant-ligatures: none. A ligature in
//     "->" or "!=" changes the glyph count, which silently shifts every cell
//     after it and turns a column of Braille into a smear.
//   - ch-based sizing, not em or px. The `ch` unit is the advance width of "0"
//     in the chosen face, which for a monospace face is the cell width; sizing
//     in px would let the container and the grid disagree.
//   - white-space: pre and a tab-size, because the content is preformatted and
//     the default HTML whitespace handling would collapse it.
//
// The colour pairings are chosen for contrast on the dark surface rather than
// for prettiness, and each caption clears 4.5:1, which is the WCAG 2.2 AA
// threshold for body text. The three widths sit side by side under a 40rem
// breakpoint instead of being stacked always: the point of capturing three
// widths is to be able to SEE them against each other, and stacking them on a
// phone is correct precisely because a phone is too narrow to show 120 columns.
const captureCSS = `/* Generated by cmd/capture. Do not edit by hand; the inline copy in
   each .html file is produced from this same source. */

:root {
  --tm-surface: #12151c;
  --tm-surface-alt: #1b202b;
  --tm-fg: #d7dce8;
  --tm-muted: #98a2b6;
  --tm-accent: #7fb0ff;
  --tm-border: #333c4d;
  --tm-mono: ui-monospace, "SF Mono", "DejaVu Sans Mono", "Cascadia Mono",
             "Liberation Mono", Menlo, Consolas, monospace;
}

@media (prefers-color-scheme: light) {
  :root {
    --tm-surface: #f7f8fb;
    --tm-surface-alt: #eef1f7;
    --tm-fg: #1d222c;
    --tm-muted: #5a6478;
    --tm-accent: #2f6fd0;
    --tm-border: #cdd4e0;
  }
}

body {
  margin: 0;
  padding: 1.5rem;
  background: var(--tm-surface);
  color: var(--tm-fg);
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  line-height: 1.5;
}

.tm-name { font-size: 1.35rem; margin: 0 0 .25rem; }
.tm-meta { margin: .1rem 0; color: var(--tm-muted); font-size: .85rem; }
.tm-note {
  margin: .6rem 0 0;
  padding: .5rem .7rem;
  border-left: 3px solid var(--tm-accent);
  background: var(--tm-surface-alt);
  color: var(--tm-muted);
  font-size: .85rem;
}

.tm-widths { display: flex; gap: 1rem; overflow-x: auto; margin: 1rem 0; }
.tm-width { flex: 0 0 auto; }
.tm-cap { margin: 0 0 .3rem; color: var(--tm-muted); font-size: .75rem; }

.tm-plain-head {
  margin: 1.5rem 0 .4rem;
  color: var(--tm-muted);
  font-size: .85rem;
}

/* The capture itself. Everything that keeps the grid square is on this rule
   and nowhere else, so a change to terminal fidelity is a change in one place. */
.tm-capture {
  margin: 0;
  padding: .7rem .8rem;
  background: var(--tm-surface-alt);
  border: 1px solid var(--tm-border);
  border-radius: 3px;
  color: var(--tm-fg);
  font-family: var(--tm-mono);
  font-size: 14px;
  font-variant-ligatures: none;
  font-feature-settings: "liga" 0, "calt" 0;
  line-height: 1.3;
  white-space: pre;
  tab-size: 8;
  overflow-x: auto;
}

/* A colour run, emitted only when the run differs from its neighbours. */
.tm-fg { color: var(--tm-fg); }
.tm-bg { background: var(--tm-surface); }

/* The cursor. MemorySink.Cursor() reports position and visibility, so the mark
   is exact; it is hollow rather than solid because a terminal cursor sits UNDER
   a glyph rather than on top of it, and a static frame cannot show it blinking.
   The underline keeps it legible over a Braille or block-element cell. */
.tm-cursor {
  outline: 1px dotted var(--tm-accent);
  outline-offset: -1px;
  text-decoration: underline;
  text-decoration-style: dotted;
  text-underline-offset: .18em;
}

@media (max-width: 40rem) {
  .tm-widths { flex-direction: column; }
}
`

// runKey identifies a span of cells with identical rendition, so consecutive
// cells sharing it collapse into one HTML span.
type runKey struct {
	fg   buffer.Colour
	bg   buffer.Colour
	attr buffer.Attr
}

// renderHTML renders the whole widget page: the header, the colour capture at
// each width, and the plain-text capture.
//
// One file per widget rather than one page per width, because the three widths
// are a single piece of evidence — degradation across widths — and splitting
// them would let a reader see one width without seeing the comparison that gives
// it meaning.
func renderHTML(e Entry, captures []capture) string {
	var b strings.Builder

	b.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	b.WriteString("<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	b.WriteString("<title>TermMosaic — " + html.EscapeString(e.Name) + " capture</title>\n")
	b.WriteString("<link rel=\"stylesheet\" href=\"" + cssFile + "\">\n")
	b.WriteString("</head>\n<body>\n")

	b.WriteString("<article class=\"tm-widget\" data-widget=\"" + html.EscapeString(e.Name) +
		"\" data-package=\"" + html.EscapeString(e.Package) + "\">\n")
	b.WriteString("<h1 class=\"tm-name\">" + html.EscapeString(e.Name) + "</h1>\n")
	b.WriteString("<p class=\"tm-meta\"><code>" + html.EscapeString(e.Constructor) + "</code> &mdash; <code>" +
		html.EscapeString(e.Package) + "</code></p>\n")
	b.WriteString("<p class=\"tm-meta\">" + html.EscapeString(e.Summary) + "</p>\n")
	if e.Note != "" {
		b.WriteString("<p class=\"tm-note\">" + html.EscapeString(e.Note) + "</p>\n")
	}
	if ms, ok := firstMinSize(captures); ok {
		b.WriteString("<p class=\"tm-meta\">MinSize() = " +
			strconv.Itoa(ms.W) + " &times; " + strconv.Itoa(ms.H) + " cells</p>\n")
	}

	b.WriteString("<div class=\"tm-widths\">\n")
	for _, c := range captures {
		b.WriteString(captureBlock(c))
	}
	b.WriteString("</div>\n")

	b.WriteString("<p class=\"tm-plain-head\">Plain text &mdash; the exact cell grid, trimmed per line. " +
		"This is the honest form: Braille and block-element glyphs can take a different advance width in a " +
		"web font than a terminal gives them, which breaks the alignment they depend on.</p>\n")
	b.WriteString("<pre class=\"tm-capture\" data-form=\"text\">")
	b.WriteString(html.EscapeString(plainText(captures)))
	b.WriteString("</pre>\n")

	b.WriteString("</article>\n</body>\n</html>\n")
	return b.String()
}

// firstMinSize returns the MinSize of the first capture's widget, if it has one.
// The value is widget-wide rather than width-dependent, so reading it once is
// enough and the page does not claim it varies.
func firstMinSize(captures []capture) (buffer.Size, bool) {
	if len(captures) == 0 {
		return buffer.Size{}, false
	}
	return captures[0].minSize, captures[0].hasMinSize
}

// captureBlock renders one width: a caption and the coloured cell grid.
func captureBlock(c capture) string {
	var b strings.Builder
	fmt.Fprintf(&b, "<div class=\"tm-width\" data-cols=\"%d\">\n", c.width)
	fmt.Fprintf(&b, "<p class=\"tm-cap\">%d columns &times; %d rows</p>\n", c.width, c.height)
	fmt.Fprintf(&b, "<pre class=\"tm-capture\" data-form=\"cells\" data-cols=\"%d\">", c.width)
	writeCells(&b, c.sink)
	b.WriteString("</pre>\n</div>\n")
	return b.String()
}

// writeCells writes a sink's grid as runs of identically-styled spans.
//
// The run is over the whole CELL, not over the character: two cells holding the
// same letter in different colours are two spans, and a converter that collapsed
// them would lose the distinction the widget is drawing.
//
// A cursor mark is emitted where and only where MemorySink reports one visible.
// In this headless path none is: the renderer's cursor visibility is not driven
// by widget focus, so Cursor() comes back hidden for all 22 captures today. The
// branch is kept because it costs nothing and because a capture that invented a
// cursor would be the one dishonest thing in the file — the position is real
// information, and printing it without the renderer having asked for it is not.
func writeCells(b *strings.Builder, sink *headless.MemorySink) {
	w, h := sink.Size()
	cells := sink.Cells()
	cursorX, cursorY, cursorShown := sink.Cursor()

	// One style string per distinct rendition, cached, because a 120x14 grid is
	// 1680 cells and most of them share a handful of renditions.
	cache := make(map[runKey]string)

	for y := 0; y < h; y++ {
		last := rowExtent(cells, w, y, cursorShown, cursorX, cursorY)

		var (
			open   bool
			key    runKey
			runBuf strings.Builder
		)
		flush := func() {
			if !open || runBuf.Len() == 0 {
				return
			}
			fmt.Fprintf(b, "<span style=\"%s\">%s</span>", cache[key], html.EscapeString(runBuf.String()))
			open = false
			runBuf.Reset()
		}

		for x := 0; x < last; x++ {
			cell := cells[y*w+x]
			if cell.IsContinuation() {
				// A continuation cell is the right half of a wide glyph and
				// paints nothing; emitting it would double the width of any CJK
				// content in a capture.
				continue
			}
			r := cellRune(cell)
			if cursorShown && x == cursorX && y == cursorY {
				// The cursor splits a run rather than riding inside it, so the
				// mark lands on the cell it is actually under.
				flush()
				fmt.Fprintf(b, "<span class=\"tm-cursor\">%s</span>", html.EscapeString(string(r)))
				continue
			}
			k := runKey{fg: cell.FG, bg: cell.BG, attr: cell.Attr}
			if !open || k != key {
				flush()
				key = k
				open = true
				cacheKey(k, cache)
			}
			runBuf.WriteRune(r)
		}
		flush()
		if y < h-1 {
			b.WriteByte('\n')
		}
	}
}

// cellRune returns the rune a cell displays, with the zero value meaning a
// space rather than a NUL: a never-painted cell is blank, and writing a NUL
// into a <pre> would be both wrong and invisible in a diff.
func cellRune(c buffer.Cell) rune {
	if c.Ch == 0 {
		return ' '
	}
	return c.Ch
}

// rowExtent returns the number of cells in row y that are worth emitting: the
// index after the last cell that paints something.
//
// A trailing space whose background is the terminal default and which carries no
// attribute paints nothing, so it is dropped — it would otherwise add a
// background-less span to every row of every capture. A trailing space with a
// BACKGROUND is kept, because in a Table or a Block that space is a painted band
// and dropping it would shorten the band.
//
// A cursor cell is never dropped, whatever it holds: the mark is information,
// and trimming it would put it on the wrong cell.
func rowExtent(cells []buffer.Cell, w, y int, cursorShown bool, cursorX, cursorY int) int {
	if cursorShown && y == cursorY {
		return cursorX + 1
	}
	last := w
	for last > 0 {
		c := cells[y*w+last-1]
		if c.IsContinuation() {
			last--
			continue
		}
		r := cellRune(c)
		if (r == ' ' || r == 0) && c.BG.IsDefault() && c.Attr == 0 {
			last--
			continue
		}
		break
	}
	return last
}

// cacheKey ensures cache holds an entry for k and returns it.
//
// Built eagerly rather than lazily at use because the flush closure runs after
// the key is stored, and an entry must exist by then.
func cacheKey(k runKey, cache map[runKey]string) {
	if _, ok := cache[k]; ok {
		return
	}
	cache[k] = styleFor(k)
}

// styleFor renders one rendition as a CSS declaration list.
//
// Reverse is resolved here, into swapped colours, rather than being emitted as
// an SGR the browser would have to honour: `reverse-video` is a video filter,
// not a CSS property, so emitting it would drop the attribute on the floor and
// a widget relying on reverse would capture as plain text. A default colour
// channel emits nothing at all, so it inherits the surface from capture.css
// rather than being pinned to a guessed terminal default — guessing here would
// bake one terminal's palette into every widget's picture.
func styleFor(k runKey) string {
	fg, bg := k.fg, k.bg
	if k.attr.Has(buffer.AttrReverse) {
		fg, bg = bg, fg
	}
	var parts []string
	if !fg.IsDefault() {
		parts = append(parts, "color:"+fg.Hex())
	}
	if !bg.IsDefault() {
		parts = append(parts, "background-color:"+bg.Hex())
	}
	if k.attr.Has(buffer.AttrBold) {
		parts = append(parts, "font-weight:700")
	}
	if k.attr.Has(buffer.AttrFaint) {
		parts = append(parts, "opacity:.65")
	}
	var decor []string
	if k.attr.Has(buffer.AttrUnderline) {
		decor = append(decor, "underline")
	}
	if k.attr.Has(buffer.AttrStrike) {
		decor = append(decor, "line-through")
	}
	if len(decor) > 0 {
		parts = append(parts, "text-decoration:"+strings.Join(decor, " "))
	}
	if k.attr.Has(buffer.AttrItalic) {
		parts = append(parts, "font-style:italic")
	}
	return strings.Join(parts, ";")
}
